"""add_semester_field

Revision ID: 79d71a1d2b92
Revises: g7b8c9d0e1f2
Create Date: 2026-02-19 08:52:26.834138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79d71a1d2b92'
down_revision: Union[str, None] = 'g7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('students', sa.Column('semester', sa.String(length=20), nullable=True))
    # Add subjects.semester as nullable first, backfill, then set NOT NULL
    op.add_column('subjects', sa.Column('semester', sa.String(length=20), nullable=True))
    op.execute("UPDATE subjects SET semester = '1st Semester' WHERE semester IS NULL")
    op.alter_column('subjects', 'semester', nullable=False)
    op.create_index(op.f('ix_subjects_semester'), 'subjects', ['semester'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_semester'), table_name='subjects')
    op.drop_column('subjects', 'semester')
    op.drop_column('students', 'semester')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
