"""initial tables

Revision ID: ee5d8b6c4f7e
Revises: 
Create Date: 2026-02-12 03:31:03.165412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5d8b6c4f7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('strand', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.String(length=20), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_grade_level'), 'subjects', ['grade_level'], unique=False)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_strand'), 'subjects', ['strand'], unique=False)
    op.create_index(op.f('ix_subjects_subject_code'), 'subjects', ['subject_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', 'REGISTRAR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='studentstatus'), nullable=False),
    sa.Column('school_year', sa.String(length=20), nullable=True),
    sa.Column('lrn', sa.String(length=20), nullable=True),
    sa.Column('is_returning_student', sa.Boolean(), nullable=True),
    sa.Column('grade_level_to_enroll', sa.String(length=20), nullable=True),
    sa.Column('last_grade_level_completed', sa.String(length=20), nullable=True),
    sa.Column('last_school_year_completed', sa.String(length=20), nullable=True),
    sa.Column('last_school_attended', sa.String(length=255), nullable=True),
    sa.Column('school_type', sa.Enum('PUBLIC', 'PRIVATE', name='schooltype'), nullable=True),
    sa.Column('strand', sa.String(length=50), nullable=True),
    sa.Column('school_to_enroll_in', sa.String(length=255), nullable=True),
    sa.Column('school_id', sa.String(length=50), nullable=True),
    sa.Column('school_address', sa.String(length=500), nullable=True),
    sa.Column('psa_birth_certificate_no', sa.String(length=50), nullable=True),
    sa.Column('lrn_learner_ref_no', sa.String(length=20), nullable=True),
    sa.Column('student_photo_path', sa.String(length=500), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex'), nullable=True),
    sa.Column('mother_tongue', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city_municipality', sa.String(length=100), nullable=True),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('house_no_street', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('father_full_name', sa.String(length=200), nullable=True),
    sa.Column('father_contact', sa.String(length=20), nullable=True),
    sa.Column('mother_full_name', sa.String(length=200), nullable=True),
    sa.Column('mother_contact', sa.String(length=20), nullable=True),
    sa.Column('guardian_full_name', sa.String(length=200), nullable=True),
    sa.Column('guardian_contact', sa.String(length=20), nullable=True),
    sa.Column('documents_path', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_student_number'), 'students', ['student_number'], unique=True)
    op.create_table('student_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', name='uq_student_subject')
    )
    op.create_index(op.f('ix_student_subjects_id'), 'student_subjects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_subjects_id'), table_name='student_subjects')
    op.drop_table('student_subjects')
    op.drop_index(op.f('ix_students_student_number'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_subject_code'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_strand'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_grade_level'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
